<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function countPlayedSongs($userId) {
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult("count", "count");
        return $this->getEntityManager()->createNativeQuery("SELECT COUNT(*) count FROM played__song WHERE user_id = ?", $rsm) ->setParameters(array($userId))->getSingleScalarResult();
    }
}
