# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        hwi:
            id: hwi_oauth.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    spotify:           "/login/check-spotify"
                    discogs:           "/login/check-discogs"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/spotify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-spotify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/discogs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-discogs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z], roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
