# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    my.oauth_aware.user_provider.service:
        class: AppBundle\Security\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - { spotify: 'spotifyId' }
    app.services.update_users_achievements_service:
        class: AppBundle\Services\UpdateUsersAchievementsService
        arguments: ['@doctrine.orm.default_entity_manager']
    app.services.spotify_api_service:
        class: AppBundle\Services\SpotifyApiService
        arguments: ['@doctrine.orm.default_entity_manager', '@hwi_oauth.resource_owner.spotify']
    app.services.update_user_history_service:
        class: AppBundle\Services\UpdateUserHistoryService
        arguments: ['@doctrine.orm.default_entity_manager', '@app.services.spotify_api_service']
    app.services.update_songs_service:
        class: AppBundle\Services\UpdateSongsService
        arguments: ['@doctrine.orm.default_entity_manager', '@app.services.spotify_api_service']
